name: javascript

on:
  push:
    paths:
    - '.github/workflows/javascript.yml'
    - 'javascript/**'
    - 'tests/**'

defaults:
  run:
    working-directory: javascript

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Install dependencies
        run: npm install
      - name: Test with jest
        run: npm run test
